stages:
#    - clone
    - test
#    - cleanup
    - build
    - deploy

variables:
    IMAGE_NAME: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID

#clone:
#    stage: clone
#    tags:
#        - social
#    script:
#        - git clone git@gitlab.skillbox.ru:javapro_team27/javapro_teams27_backend.git

test:
    stage: test
    tags:
        - social-server-2
    script:
#        - cd /root/javapro_teams27_backend
        - mvn clean test
    allow_failure: true


#cleanup:
#    stage: cleanup
#    tags:
#        - social
#    script:
#        - docker stop javapro_teams27_backend
#        - docker container prune
#        - docker image rm javapro_teams27_backend
#    allow_failure: true


build:
    stage: build
    tags:
        - social-server-2
    script:
#        - cd /root/javapro_teams27_backend
        - whoami
        - pwd
        - docker build -t $IMAGE_NAME ./
    only:
        - aleksei

deploy:
    stage: deploy
    tags:
        - social-server-2
    script:
#        - cd /root/javapro_teams27_backend
        - docker run -d -p 8086:8086 --name $IMAGE_NAME
    only:
        - aleksei


