stages:
    - build
    - push
    - test
    - cleanup
    - deploy

build:
    stage: build
    tags:
        - social
    script:
        - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID .

push:
    stage: push
    tags:
        - social
    before_script:
        - docker login -u
    script:
        - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID

test:
    stage: test
    tags:
        - social
    image:
        name: docker/compose:1.23.2
        entrypoint: [""]
    variables:
        - DOCKER_HOST:
    script:
        -

deploy:
    stage: deploy
    tags:
        - social
    script:
        - docker run --name social-backend -p 8086:8086 $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID

