image: docker:20.10.17

services:
    - docker:20.10.17-dind

variables:
    IMAGE_NAME: axelration/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

before_script:
    - docker info

stages:
    - build
    - push
    - deploy

docker-build:
    stage: build
    tags:
        - docker-runner
    script:
        - docker build -t IMAGE_NAME ./
    rules:
        - if: "$CI_COMMIT_BRANCH == 'aleksei'"

push:
    stage: push
    tags:
        - docker-runner
    before_script:
        - docker login -u axelration -p dckr_pat_IIHDrvsHHR-fLbTpvKz2OaktrTs
    script:
        - docker push IMAGE_NAME
    allow_failure: true

deploy:
    stage: deploy
    tags:
        - docker-runner
    variables:
        DOCKER_HOST: tcp://195.133.48.174:22
    script:
        - docker pull IMAGE_NAME
        - docker run -d -p 8086:8086 --name backend
