stages:
    - clone
    - test
    - build
    - deploy

variables:
    IMAGE_NAME: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID
    CONTAINER_NAME: javapro_teams27_backend

clone:
    stage: clone
    tags:
        - social-server-2
    script:
        - git clone git@gitlab.skillbox.ru:javapro_team27/javapro_teams27_backend.git

test:
    stage: test
    tags:
        - social-server-2
    script:
        - cd root/javapro_teams27_backend
        - mvn clean test

build:
    stage: build
    tags:
        - social-server-2
    script:
        - cd /root/javapro_teams27_backend
        - docker build -t $IMAGE_NAME ./
    only:
        - aleksei

deploy:
    stage: deploy
    tags:
        - social-server-2
    script:
        - cd /root/javapro_teams27_backend
        - docker run -d -p 8086:8086 --name CONTAINER_NAME $IMAGE_NAME
    only:
        - aleksei

