stages:
#    - clone
    - test
    - build
    - release
    - deploy

variables:
    IMAGE_NAME_BUILD: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}.${CI_PIPELINE_ID}
    IMAGE_NAME_RELEASE: ${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
    CONTAINER_NAME: javapro_teams27_backend

#clone:
#    stage: clone
#    tags:
#        - social-server-2
#    script:
#        - git clone git@gitlab.skillbox.ru:javapro_team27/javapro_teams27_backend.git

test:
    stage: test
    tags:
        - social-server-2
    script:
        - mvn clean test

build:
    stage: build
    tags:
        - social-server-2
    script:
        - docker build -t $IMAGE_NAME_BUILD ./
    only:
        - aleksei

release:
    stage: release
    tags:
        - social-server-2
    before_script:
        - docker stop $CONTAINER_NAME || exit_code=0
        - docker container prune || exit_code=0
        - docker rmi $IMAGE_NAME_RELEASE || exit_code=0
    script:
        - docker tag $IMAGE_NAME_BUILD $IMAGE_NAME_RELEASE

deploy:
    stage: deploy
    tags:
        - social-server-2
    script:
        - docker run -d -p 8086:8086 --name $CONTAINER_NAME $IMAGE_NAME_RELEASE
