stages:
    - clone
    - test
    - cleanup
    - build
    - deploy

clone:
    stage: clone
    tags:
        - social-network
    script:
        - cd /root
        - git clone git@gitlab.skillbox.ru:javapro_team27/javapro_teams27_backend.git

test:
    stage: test
    tags:
        - social-network
    script:
        - cd /root/javapro_teams27_backend
        - mvn clean test

cleanup:
    stage: cleanup
    tags:
        - social-network
    script:
        - docker stop javapro_teams27_backend
        - docker container prune
        - docker image rm javapro_teams27_backend

build:
    stage: build
    tags:
        - social-docker
    script:
        - cd /root/javapro_teams27_backend
        - docker build -t javapro_teams27_backend:$CI_PIPELINE_ID .
    only:
        - aleksei

deploy:
    stage: deploy
    tags:
        - social-network
    script:
        - cd /root/javapro_teams27_backend
        - docker run -d -p 8086:8086 --name javapro_teams27_backend:$CI_PIPELINE_ID
    only:
        - aleksei