stages:
#    - test
    - build
    - deploy

variables:
    CONTAINER_NAME: social-backend
#    DOCKER_REGISTRY: registry-1.docker.io
    TAG_LATEST: $DOCKER_USER/$CI_COMMIT_REF_NAME:latest
    TAG_COMMIT: axelration/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA


#test:
#    image: maven:3.8.6-jdk-11-slim
#    stage: test
#    tags:
#        - social-docker
#    script:
#        - mvn clean test
#    artifacts:
#        when: always
#        reports:
#            junit:
#                - target/surefire-reports/TEST-*.xml

build:
    image: docker:20.10.17
    stage: build
    tags:
        - social-docker
    services:
        - name: docker:20.10.17-dind
          command: ["--tsl=false"]
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay2
        DOCKER_TSL_CERTDIR: ""
    script:
        - docker build -t $TAG_COMMIT .
        - docker login -u axelration -p vmnxttya5r2c registry-1.docker-io
        - docker push $TAG_COMMIT

deploy:
    image: openjdk:11-slim
    stage: deploy
    tags:
        - social-docker
    script:
        - chmod og= $ID_RSA
        - apk update && apk add openssh-client
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u axelration -p vmnxttya5r2c"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $CONTAINER_NAME || true"
        - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 8086:8086 --name $CONTAINER_NAME $TAG_COMMIT"
    environment:
        name: prod
        url: http://195.133.48.174
    only:
        - aleksei