image: docker:20.10.17

services:
    - docker:20.10.17-dind

variables:
    IMAGE_NAME: axelration/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

stages:
    - build
    - push
    - deploy

docker-build:
    stage: build
    tags:
        - docker-runner
    script:
        - docker build -t $IMAGE_NAME ./
        - docker login -u axelration -p dckr_pat_IIHDrvsHHR-fLbTpvKz2OaktrTs
        - docker push $IMAGE_NAME
        - docker pull $IMAGE_NAME
        - docker run -d -p 8086:8086 --name backend
    rules:
        - if: "$CI_COMMIT_BRANCH == 'aleksei'"

push:
    stage: push
    tags:
        - docker-runner


    allow_failure: true

deploy:
    stage: deploy
    tags:
        - docker-runner


