image: docker:20.10.17

services:
    - docker:20.10.17-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

before_script:
    - docker info

stages:
    - build
#    - maven-test
#    - url-test
#    - cleanup
    - deploy

docker-build:
    stage: build
    tags:
        - social-docker
    script:
        - docker build -t $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID ./
    rules:
        - if: "$CI_COMMIT_BRANCH == 'aleksei'"

#maven-test:
#    stage: maven-test
#    tags:
#        - social-docker
#    script:
#        - mvn verify
#    artifacts:
#        when: always
#        reports:
#            junit:
#                - target/surefire-reports/TEST-*.xml

#url-test:
#    stage: url-test
#    tags:
#        - social-docker
#    image:
#        name: docker/compose:1.25.0
#        entrypoint: [""]
#    variables:
#        DOCKER_HOST: tcp://195.133.48.174
#    before_script:
#        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#    script:
#        - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from test
#
#cleanup:
#    stage: cleanup
#    tags:
#        - social-docker
#    image:
#        name: docker/compose:1.25.0
#        entrypoint: [""]
#    variables:
#        DOCKER_HOST: tcp://195.133.48.174
#    script:
#        - docker-compose down
#    when: always

deploy:
    stage: deploy
    tags:
        - social-docker
    image:
        name: docker/compose:1.25.0
        entrypoint: [""]
    variables:
        DOCKER_HOST: tcp://195.133.48.174:22
    script:
        - docker-compose -f docker-compose.prod.yml up -d

