image: docker:20.10.17

services:
    - docker:20.10.17-dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

before_script:
    - docker info

stages:
    - test
    - build
    - deploy

maven-test:
    stage: test
    tags:
        - social-docker
    script:
        - mvn clear test
    artifacts:
        when: always
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
    allow_failure: true

build:
    stage: build
    tags:
        - social-docker
    script:
        - docker build -t $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:${CI_COMMIT_REF_SLUG}_backend.$CI_PIPELINE_ID ./
    rules:
        - if: "$CI_COMMIT_BRANCH == 'aleksei'"

deploy:
    stage: deploy
    tags:
        - social-docker
    image:
        name: docker/compose:1.25.0
        entrypoint: [""]
#    variables:
#        DOCKER_HOST: tcp://195.133.48.174:22
    script:
        - docker

