#server:
#    port: 8086
#
#spring:
#    datasource:
#        driver-class-name: org.postgresql.Driver
#        url: ${DATASOURCE_URL}
#        username:  ${DATASOURCE_USER}
#        password: ${DATASOURCE_PASS}
#    liquibase:
#        enabled: true
#
#logging:
#    level:
#        root: info


server:
    port: 8080

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: root
    liquibase:
        enabled: true

logging:
    level:
        root: info


