server:
    port: 8086

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DATASOURCE_URL}
        username:  ${DATASOURCE_USER}
        password: ${DATASOURCE_PASS}
    liquibase:
        enabled: false

logging:
    level:
        root: info


